### ISSUE TITLE
The problem about grid_sample in  tpv_aggregator.py

### ISSUE THREAD

**Issue by yyuxin** [wzzheng/PointOcc#1]
Thanks for your work! However, I find this part of code a little confusing
https://github.com/wzzheng/PointOcc/blob/53a102dae184e96049f109ad66c44eaa8bd59829/model/tpv_aggregator.py#L104
shouldn't the denominator (self.tpv_w*self.scale_w) be (self.tpv_w*self.scale_w-1) here? Or is there any special design here

**Comment by zuosc19** [comment]
Thanks for your great question! In our approach, we consider the pixels of tpv planes as squares rather than points. When sampling features, we set the param `align_corners=False`, which means that the extrema (-1 and 1) are considered as referring to the corner points of the tpv's corner pixels. As a result, the sampling locations vary within the range `[0, tpv_w*scale_w]`, and the normalization factor should be `tpv_w*scale_w` instead of `tpv_w*scale_w-1`.
