### ISSUE TITLE
The problem about volume_space 

### ISSUE THREAD

**Issue by Naclzno** [wzzheng/PointOcc#8]
Thank you for your work！

I'm examining the parameters max_volume_space = [50, 3.1415926, 3] and min_volume_space = [0, -3.1415926, -5], which define the maximum and minimum volume space for processing data. After converting these to arrays with np.asarray, I calculate the range of each dimension as crop_range = max_bound - min_bound, resulting in [50, 6.2831852 (2π), 8].

My questions are:

1. How were the ranges for the radius and height ([50, 2π, 8]) determined? Is there a specific rationale or dataset characteristic that guided these choices?

2. Regarding the line xyz_pol_grid = np.clip(xyz_pol, min_bound, max_bound - 1e-3), I'm concerned about the potential modification of the original point positions. By clipping with max_bound - 1e-3, does it not alter the spatial coordinates slightly, especially for points near the boundary? What's the intent behind this adjustment?

**Comment by zuosc19** [comment]
Thanks for your insightful questions!
Q1: In the nuScenes dataset, most lidar points are in the range of [-50, -50, -5] ~ [50, 50, 3], and [0, -π, -5] ~ [50, π, 3] is exactly the corresponding range in the cylindrical coordinate system. So we clip the points to this range, like most methods do.
Q2: To avoid index overflow for points that fall exactly on the maximum boundary when calculating grid_ind, we clip points with max_bound - 1e-5 instead of max_bound, though this may slightly disturb the position of points near the boundary.

**Comment by Naclzno** [comment]
Thank you very much for your answer!
